package com.qianyan.lab.core.repo.bean;

public class SysEntityAttrDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer entityGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_attr_name_en
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entityAttrNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_attr_name_ch
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entityAttrNameCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_attr_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entityAttrDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_save_table
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entitySaveTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_save_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entitySaveField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.entity_save_type
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String entitySaveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_default_value
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrDefaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_one_to_many_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer attrOneToManyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_can_variable
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer attrCanVariable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_rule_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrRuleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_front_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrFrontCheckRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_back_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrBackCheckRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_value_modify_monitor
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer attrValueModifyMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_value_modify_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrValueModifyRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_rel_entity
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrRelEntity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_rel_entity_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrRelEntityField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_value_name_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrValueNameFunc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.delete_caseade_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer deleteCaseadeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.can_result_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer canResultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.can_condition_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer canConditionFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.can_order_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer canOrderFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.attr_front_slt_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private String attrFrontSltRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_attr_def.is_support_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    private Integer isSupportFunc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_group_id
     *
     * @return the value of sys_entity_attr_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getEntityGroupId() {
        return entityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_group_id
     *
     * @param entityGroupId the value for sys_entity_attr_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntityGroupId(Integer entityGroupId) {
        this.entityGroupId = entityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_attr_name_en
     *
     * @return the value of sys_entity_attr_def.entity_attr_name_en
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntityAttrNameEn() {
        return entityAttrNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_attr_name_en
     *
     * @param entityAttrNameEn the value for sys_entity_attr_def.entity_attr_name_en
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntityAttrNameEn(String entityAttrNameEn) {
        this.entityAttrNameEn = entityAttrNameEn == null ? null : entityAttrNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_attr_name_ch
     *
     * @return the value of sys_entity_attr_def.entity_attr_name_ch
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntityAttrNameCh() {
        return entityAttrNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_attr_name_ch
     *
     * @param entityAttrNameCh the value for sys_entity_attr_def.entity_attr_name_ch
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntityAttrNameCh(String entityAttrNameCh) {
        this.entityAttrNameCh = entityAttrNameCh == null ? null : entityAttrNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_attr_desc
     *
     * @return the value of sys_entity_attr_def.entity_attr_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntityAttrDesc() {
        return entityAttrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_attr_desc
     *
     * @param entityAttrDesc the value for sys_entity_attr_def.entity_attr_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntityAttrDesc(String entityAttrDesc) {
        this.entityAttrDesc = entityAttrDesc == null ? null : entityAttrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_save_table
     *
     * @return the value of sys_entity_attr_def.entity_save_table
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntitySaveTable() {
        return entitySaveTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_save_table
     *
     * @param entitySaveTable the value for sys_entity_attr_def.entity_save_table
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntitySaveTable(String entitySaveTable) {
        this.entitySaveTable = entitySaveTable == null ? null : entitySaveTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_save_field
     *
     * @return the value of sys_entity_attr_def.entity_save_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntitySaveField() {
        return entitySaveField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_save_field
     *
     * @param entitySaveField the value for sys_entity_attr_def.entity_save_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntitySaveField(String entitySaveField) {
        this.entitySaveField = entitySaveField == null ? null : entitySaveField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.entity_save_type
     *
     * @return the value of sys_entity_attr_def.entity_save_type
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getEntitySaveType() {
        return entitySaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.entity_save_type
     *
     * @param entitySaveType the value for sys_entity_attr_def.entity_save_type
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setEntitySaveType(String entitySaveType) {
        this.entitySaveType = entitySaveType == null ? null : entitySaveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_default_value
     *
     * @return the value of sys_entity_attr_def.attr_default_value
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrDefaultValue() {
        return attrDefaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_default_value
     *
     * @param attrDefaultValue the value for sys_entity_attr_def.attr_default_value
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrDefaultValue(String attrDefaultValue) {
        this.attrDefaultValue = attrDefaultValue == null ? null : attrDefaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_one_to_many_flag
     *
     * @return the value of sys_entity_attr_def.attr_one_to_many_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getAttrOneToManyFlag() {
        return attrOneToManyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_one_to_many_flag
     *
     * @param attrOneToManyFlag the value for sys_entity_attr_def.attr_one_to_many_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrOneToManyFlag(Integer attrOneToManyFlag) {
        this.attrOneToManyFlag = attrOneToManyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_can_variable
     *
     * @return the value of sys_entity_attr_def.attr_can_variable
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getAttrCanVariable() {
        return attrCanVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_can_variable
     *
     * @param attrCanVariable the value for sys_entity_attr_def.attr_can_variable
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrCanVariable(Integer attrCanVariable) {
        this.attrCanVariable = attrCanVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_rule_desc
     *
     * @return the value of sys_entity_attr_def.attr_rule_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrRuleDesc() {
        return attrRuleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_rule_desc
     *
     * @param attrRuleDesc the value for sys_entity_attr_def.attr_rule_desc
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrRuleDesc(String attrRuleDesc) {
        this.attrRuleDesc = attrRuleDesc == null ? null : attrRuleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_front_check_rule
     *
     * @return the value of sys_entity_attr_def.attr_front_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrFrontCheckRule() {
        return attrFrontCheckRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_front_check_rule
     *
     * @param attrFrontCheckRule the value for sys_entity_attr_def.attr_front_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrFrontCheckRule(String attrFrontCheckRule) {
        this.attrFrontCheckRule = attrFrontCheckRule == null ? null : attrFrontCheckRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_back_check_rule
     *
     * @return the value of sys_entity_attr_def.attr_back_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrBackCheckRule() {
        return attrBackCheckRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_back_check_rule
     *
     * @param attrBackCheckRule the value for sys_entity_attr_def.attr_back_check_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrBackCheckRule(String attrBackCheckRule) {
        this.attrBackCheckRule = attrBackCheckRule == null ? null : attrBackCheckRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_value_modify_monitor
     *
     * @return the value of sys_entity_attr_def.attr_value_modify_monitor
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getAttrValueModifyMonitor() {
        return attrValueModifyMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_value_modify_monitor
     *
     * @param attrValueModifyMonitor the value for sys_entity_attr_def.attr_value_modify_monitor
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrValueModifyMonitor(Integer attrValueModifyMonitor) {
        this.attrValueModifyMonitor = attrValueModifyMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_value_modify_rule
     *
     * @return the value of sys_entity_attr_def.attr_value_modify_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrValueModifyRule() {
        return attrValueModifyRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_value_modify_rule
     *
     * @param attrValueModifyRule the value for sys_entity_attr_def.attr_value_modify_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrValueModifyRule(String attrValueModifyRule) {
        this.attrValueModifyRule = attrValueModifyRule == null ? null : attrValueModifyRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_rel_entity
     *
     * @return the value of sys_entity_attr_def.attr_rel_entity
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrRelEntity() {
        return attrRelEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_rel_entity
     *
     * @param attrRelEntity the value for sys_entity_attr_def.attr_rel_entity
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrRelEntity(String attrRelEntity) {
        this.attrRelEntity = attrRelEntity == null ? null : attrRelEntity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_rel_entity_field
     *
     * @return the value of sys_entity_attr_def.attr_rel_entity_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrRelEntityField() {
        return attrRelEntityField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_rel_entity_field
     *
     * @param attrRelEntityField the value for sys_entity_attr_def.attr_rel_entity_field
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrRelEntityField(String attrRelEntityField) {
        this.attrRelEntityField = attrRelEntityField == null ? null : attrRelEntityField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_value_name_func
     *
     * @return the value of sys_entity_attr_def.attr_value_name_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrValueNameFunc() {
        return attrValueNameFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_value_name_func
     *
     * @param attrValueNameFunc the value for sys_entity_attr_def.attr_value_name_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrValueNameFunc(String attrValueNameFunc) {
        this.attrValueNameFunc = attrValueNameFunc == null ? null : attrValueNameFunc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.delete_caseade_flag
     *
     * @return the value of sys_entity_attr_def.delete_caseade_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getDeleteCaseadeFlag() {
        return deleteCaseadeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.delete_caseade_flag
     *
     * @param deleteCaseadeFlag the value for sys_entity_attr_def.delete_caseade_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setDeleteCaseadeFlag(Integer deleteCaseadeFlag) {
        this.deleteCaseadeFlag = deleteCaseadeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.can_result_flag
     *
     * @return the value of sys_entity_attr_def.can_result_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getCanResultFlag() {
        return canResultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.can_result_flag
     *
     * @param canResultFlag the value for sys_entity_attr_def.can_result_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setCanResultFlag(Integer canResultFlag) {
        this.canResultFlag = canResultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.can_condition_flag
     *
     * @return the value of sys_entity_attr_def.can_condition_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getCanConditionFlag() {
        return canConditionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.can_condition_flag
     *
     * @param canConditionFlag the value for sys_entity_attr_def.can_condition_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setCanConditionFlag(Integer canConditionFlag) {
        this.canConditionFlag = canConditionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.can_order_flag
     *
     * @return the value of sys_entity_attr_def.can_order_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getCanOrderFlag() {
        return canOrderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.can_order_flag
     *
     * @param canOrderFlag the value for sys_entity_attr_def.can_order_flag
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setCanOrderFlag(Integer canOrderFlag) {
        this.canOrderFlag = canOrderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.attr_front_slt_rule
     *
     * @return the value of sys_entity_attr_def.attr_front_slt_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public String getAttrFrontSltRule() {
        return attrFrontSltRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.attr_front_slt_rule
     *
     * @param attrFrontSltRule the value for sys_entity_attr_def.attr_front_slt_rule
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setAttrFrontSltRule(String attrFrontSltRule) {
        this.attrFrontSltRule = attrFrontSltRule == null ? null : attrFrontSltRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_attr_def.is_support_func
     *
     * @return the value of sys_entity_attr_def.is_support_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public Integer getIsSupportFunc() {
        return isSupportFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_attr_def.is_support_func
     *
     * @param isSupportFunc the value for sys_entity_attr_def.is_support_func
     *
     * @mbggenerated Wed Jan 20 13:18:53 CST 2016
     */
    public void setIsSupportFunc(Integer isSupportFunc) {
        this.isSupportFunc = isSupportFunc;
    }
}