package com.qianyan.lab.core.repo.bean;

public class SysEntityGroupDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private Integer entityGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_name
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_level
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private Integer entityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_group_name_en
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private String entityGroupNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_group_name_ch
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private String entityGroupNameCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_group_desc
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private String entityGroupDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entity_group_def.entity_group_status
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    private Integer entityGroupStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_group_id
     *
     * @return the value of sys_entity_group_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public Integer getEntityGroupId() {
        return entityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_group_id
     *
     * @param entityGroupId the value for sys_entity_group_def.entity_group_id
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityGroupId(Integer entityGroupId) {
        this.entityGroupId = entityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_name
     *
     * @return the value of sys_entity_group_def.entity_name
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_name
     *
     * @param entityName the value for sys_entity_group_def.entity_name
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_level
     *
     * @return the value of sys_entity_group_def.entity_level
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public Integer getEntityLevel() {
        return entityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_level
     *
     * @param entityLevel the value for sys_entity_group_def.entity_level
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityLevel(Integer entityLevel) {
        this.entityLevel = entityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_group_name_en
     *
     * @return the value of sys_entity_group_def.entity_group_name_en
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public String getEntityGroupNameEn() {
        return entityGroupNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_group_name_en
     *
     * @param entityGroupNameEn the value for sys_entity_group_def.entity_group_name_en
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityGroupNameEn(String entityGroupNameEn) {
        this.entityGroupNameEn = entityGroupNameEn == null ? null : entityGroupNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_group_name_ch
     *
     * @return the value of sys_entity_group_def.entity_group_name_ch
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public String getEntityGroupNameCh() {
        return entityGroupNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_group_name_ch
     *
     * @param entityGroupNameCh the value for sys_entity_group_def.entity_group_name_ch
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityGroupNameCh(String entityGroupNameCh) {
        this.entityGroupNameCh = entityGroupNameCh == null ? null : entityGroupNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_group_desc
     *
     * @return the value of sys_entity_group_def.entity_group_desc
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public String getEntityGroupDesc() {
        return entityGroupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_group_desc
     *
     * @param entityGroupDesc the value for sys_entity_group_def.entity_group_desc
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityGroupDesc(String entityGroupDesc) {
        this.entityGroupDesc = entityGroupDesc == null ? null : entityGroupDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entity_group_def.entity_group_status
     *
     * @return the value of sys_entity_group_def.entity_group_status
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public Integer getEntityGroupStatus() {
        return entityGroupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entity_group_def.entity_group_status
     *
     * @param entityGroupStatus the value for sys_entity_group_def.entity_group_status
     *
     * @mbggenerated Wed Jan 20 13:17:44 CST 2016
     */
    public void setEntityGroupStatus(Integer entityGroupStatus) {
        this.entityGroupStatus = entityGroupStatus;
    }
}